// Auto-generated one-time seed for a fresh/empty backend database, matching
// the frontend's src/data/seed.ts (real task list as of 29 July 2026 calendar brief).
// Only used when the tasks table is empty — see connection.ts.
import type { TaskRecord } from '../types.js';

export const SEED_TASKS: TaskRecord[] = [
  {
    id: 'task-1',
    title: 'Martyn\'s Law — General Email',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'not-started' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: null,
    startDate: null,
    campaignId: null,
    createdAt: '2026-07-01T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-2',
    title: 'Account Manager Email — Matt Ellwood-Smith (Radio Links)',
    notes: '',
    brand: 'radio-links' as TaskRecord['brand'],
    status: 'in-progress' as TaskRecord['status'],
    priority: 'high' as TaskRecord['priority'],
    deadline: '2026-07-23T00:00:00.000Z',
    startDate: '2026-07-20T00:00:00.000Z',
    campaignId: 'campaign-2',
    createdAt: '2026-07-20T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-3',
    title: 'Account Manager Email — Matt Ellwood-Smith (Capcom)',
    notes: '',
    brand: 'capcom' as TaskRecord['brand'],
    status: 'in-progress' as TaskRecord['status'],
    priority: 'high' as TaskRecord['priority'],
    deadline: '2026-07-23T00:00:00.000Z',
    startDate: '2026-07-20T00:00:00.000Z',
    campaignId: 'campaign-2',
    createdAt: '2026-07-20T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-4',
    title: 'Account Manager Email — Alex Bacon',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'high' as TaskRecord['priority'],
    deadline: '2026-07-23T00:00:00.000Z',
    startDate: '2026-07-20T00:00:00.000Z',
    campaignId: 'campaign-2',
    createdAt: '2026-07-20T00:00:00.000Z',
    completedAt: '2026-07-22T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-5',
    title: 'S1 Minis Email Campaign',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'not-started' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: null,
    startDate: null,
    campaignId: null,
    createdAt: '2026-07-01T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-6',
    title: 'Radio Systems new page',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'high' as TaskRecord['priority'],
    deadline: '2026-07-07T00:00:00.000Z',
    startDate: '2026-07-01T00:00:00.000Z',
    campaignId: 'campaign-3',
    createdAt: '2026-07-01T00:00:00.000Z',
    completedAt: '2026-07-07T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-7',
    title: 'Two-Way Radios product cards (6 cards)',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'high' as TaskRecord['priority'],
    deadline: '2026-07-07T00:00:00.000Z',
    startDate: '2026-07-01T00:00:00.000Z',
    campaignId: 'campaign-3',
    createdAt: '2026-07-01T00:00:00.000Z',
    completedAt: '2026-07-07T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-8',
    title: 'BC Home Page — reword + banners',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'high' as TaskRecord['priority'],
    deadline: '2026-07-07T00:00:00.000Z',
    startDate: '2026-07-01T00:00:00.000Z',
    campaignId: 'campaign-3',
    createdAt: '2026-07-01T00:00:00.000Z',
    completedAt: '2026-07-07T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-9',
    title: 'Capcom Website Banner',
    notes: '',
    brand: 'capcom' as TaskRecord['brand'],
    status: 'not-started' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: null,
    startDate: null,
    campaignId: null,
    createdAt: '2026-07-01T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-10',
    title: 'Review PPC ads — correct messaging',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'high' as TaskRecord['priority'],
    deadline: '2026-07-25T00:00:00.000Z',
    startDate: null,
    campaignId: 'campaign-1',
    createdAt: '2026-07-15T00:00:00.000Z',
    completedAt: '2026-07-25T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-11',
    title: 'PPC Campaign Restructure — Phase 1',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'high' as TaskRecord['priority'],
    deadline: null,
    startDate: '2026-07-15T00:00:00.000Z',
    campaignId: 'campaign-1',
    createdAt: '2026-07-15T00:00:00.000Z',
    completedAt: '2026-07-24T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-12',
    title: 'Martyn\'s Law — General Social Post',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'not-started' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: null,
    startDate: null,
    campaignId: null,
    createdAt: '2026-07-01T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-13',
    title: 'HSBC Social Posts',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'not-started' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: null,
    startDate: null,
    campaignId: null,
    createdAt: '2026-07-01T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-14',
    title: 'Case Study Spreadsheet — keep UTD',
    notes: '',
    brand: 'mtech' as TaskRecord['brand'],
    status: 'in-progress' as TaskRecord['status'],
    priority: 'low' as TaskRecord['priority'],
    deadline: null,
    startDate: null,
    campaignId: null,
    createdAt: '2026-07-01T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-15',
    title: 'Rebrand Case Studies — MTech Branding',
    notes: '',
    brand: 'mtech' as TaskRecord['brand'],
    status: 'not-started' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: null,
    startDate: null,
    campaignId: null,
    createdAt: '2026-07-01T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-16',
    title: 'IRCL — stickers, leaflets, MTech tape',
    notes: '',
    brand: 'ircl' as TaskRecord['brand'],
    status: 'waiting-john' as TaskRecord['status'],
    priority: 'high' as TaskRecord['priority'],
    deadline: '2026-07-23T00:00:00.000Z',
    startDate: '2026-07-15T00:00:00.000Z',
    campaignId: null,
    createdAt: '2026-07-15T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: true,
    approver: 'john' as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-17',
    title: 'VoCoVo pricing update',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'high' as TaskRecord['priority'],
    deadline: '2026-07-04T00:00:00.000Z',
    startDate: '2026-07-01T00:00:00.000Z',
    campaignId: null,
    createdAt: '2026-07-01T00:00:00.000Z',
    completedAt: '2026-07-04T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-18',
    title: 'Update Radio Communications page',
    notes: 'Edits from Climbing Trees CRO report ready to implement',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'not-started' as TaskRecord['status'],
    priority: 'high' as TaskRecord['priority'],
    deadline: null,
    startDate: null,
    campaignId: null,
    createdAt: '2026-07-27T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-19',
    title: 'Communication Systems page — Climbing Trees CRO fixes',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'not-started' as TaskRecord['status'],
    priority: 'high' as TaskRecord['priority'],
    deadline: null,
    startDate: null,
    campaignId: null,
    createdAt: '2026-07-27T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-20',
    title: 'Edit Education Industry page',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'not-started' as TaskRecord['status'],
    priority: 'high' as TaskRecord['priority'],
    deadline: null,
    startDate: null,
    campaignId: null,
    createdAt: '2026-07-27T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-21',
    title: 'Service and Repair Email Campaign — All Brands (Quarterly)',
    notes: '',
    brand: 'mtech' as TaskRecord['brand'],
    status: 'not-started' as TaskRecord['status'],
    priority: 'high' as TaskRecord['priority'],
    deadline: null,
    startDate: null,
    campaignId: null,
    createdAt: '2026-07-27T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-22',
    title: 'Review Calendly vs Microsoft Bookings',
    notes: '',
    brand: 'mtech' as TaskRecord['brand'],
    status: 'not-started' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: null,
    startDate: null,
    campaignId: null,
    createdAt: '2026-07-27T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-23',
    title: 'Q3 Education Campaign — MTech Group Email',
    notes: '',
    brand: 'mtech' as TaskRecord['brand'],
    status: 'not-started' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: '2026-08-31T00:00:00.000Z',
    startDate: null,
    campaignId: null,
    createdAt: '2026-07-27T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-24',
    title: 'Q3 Education Campaign — Social Posts',
    notes: '',
    brand: 'mtech' as TaskRecord['brand'],
    status: 'not-started' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: '2026-08-31T00:00:00.000Z',
    startDate: null,
    campaignId: null,
    createdAt: '2026-07-27T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-25',
    title: 'Q3 Education Campaign — Update landing page',
    notes: '',
    brand: 'mtech' as TaskRecord['brand'],
    status: 'not-started' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: '2026-08-31T00:00:00.000Z',
    startDate: null,
    campaignId: null,
    createdAt: '2026-07-27T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-26',
    title: 'Q3 Education Campaign — Landing page PPC review',
    notes: '',
    brand: 'mtech' as TaskRecord['brand'],
    status: 'not-started' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: '2026-08-31T00:00:00.000Z',
    startDate: null,
    campaignId: null,
    createdAt: '2026-07-27T00:00:00.000Z',
    completedAt: null,
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-27',
    title: 'Account Manager Email — Garreth Breen',
    notes: '',
    brand: 'ircl' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: null,
    startDate: '2026-07-02T00:00:00.000Z',
    campaignId: null,
    createdAt: '2026-07-02T00:00:00.000Z',
    completedAt: '2026-07-05T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-28',
    title: 'Account Manager Email — Sue Gunnell',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: null,
    startDate: '2026-07-02T00:00:00.000Z',
    campaignId: 'campaign-2',
    createdAt: '2026-07-02T00:00:00.000Z',
    completedAt: '2026-07-06T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-29',
    title: 'Account Manager Email — Sateen Baxter',
    notes: '',
    brand: 'radio-links' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: null,
    startDate: '2026-07-08T00:00:00.000Z',
    campaignId: 'campaign-2',
    createdAt: '2026-07-08T00:00:00.000Z',
    completedAt: '2026-07-11T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-30',
    title: 'YESSS Electrical email — Lydia',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: null,
    startDate: '2026-07-03T00:00:00.000Z',
    campaignId: null,
    createdAt: '2026-07-03T00:00:00.000Z',
    completedAt: '2026-07-09T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-31',
    title: 'Vistry email — Lydia',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: null,
    startDate: '2026-07-10T00:00:00.000Z',
    campaignId: null,
    createdAt: '2026-07-10T00:00:00.000Z',
    completedAt: '2026-07-15T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-32',
    title: 'BC Home Page banner — live',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: null,
    startDate: '2026-07-16T00:00:00.000Z',
    campaignId: 'campaign-3',
    createdAt: '2026-07-16T00:00:00.000Z',
    completedAt: '2026-07-19T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-33',
    title: 'Duke of York case study',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: null,
    startDate: '2026-07-05T00:00:00.000Z',
    campaignId: null,
    createdAt: '2026-07-05T00:00:00.000Z',
    completedAt: '2026-07-14T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-34',
    title: 'Hire Stickers — James Smart',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: null,
    startDate: '2026-07-12T00:00:00.000Z',
    campaignId: null,
    createdAt: '2026-07-12T00:00:00.000Z',
    completedAt: '2026-07-17T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-35',
    title: 'HSBC Social Posts',
    notes: '',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: null,
    startDate: '2026-07-01T00:00:00.000Z',
    campaignId: null,
    createdAt: '2026-07-01T00:00:00.000Z',
    completedAt: '2026-07-06T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-36',
    title: 'IRCL — stickers, leaflets, MTech tape',
    notes: '',
    brand: 'ircl' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'high' as TaskRecord['priority'],
    deadline: null,
    startDate: '2026-06-25T00:00:00.000Z',
    campaignId: null,
    createdAt: '2026-06-25T00:00:00.000Z',
    completedAt: '2026-07-02T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'task' as TaskRecord['type'],
    recipients: null,
    subject: null,
  },
  {
    id: 'task-37',
    title: 'Service and Repair Email — Brentwood',
    notes: 'SENT 29 Jul 2026 — 6,044 recipients',
    brand: 'brentwood' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: '2026-07-29T00:00:00.000Z',
    startDate: '2026-07-29T00:00:00.000Z',
    campaignId: null,
    createdAt: '2026-07-29T00:00:00.000Z',
    completedAt: '2026-07-29T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'email-send' as TaskRecord['type'],
    recipients: 6044,
    subject: 'Service & Repair — Brentwood',
  },
  {
    id: 'task-38',
    title: 'Service and Repair Email — Capcom',
    notes: 'SENT 29 Jul 2026 — 1,554 recipients',
    brand: 'capcom' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: '2026-07-29T00:00:00.000Z',
    startDate: '2026-07-29T00:00:00.000Z',
    campaignId: null,
    createdAt: '2026-07-29T00:00:00.000Z',
    completedAt: '2026-07-29T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'email-send' as TaskRecord['type'],
    recipients: 1554,
    subject: 'Service & Repair — Capcom',
  },
  {
    id: 'task-39',
    title: 'Service and Repair Email — Radio Links',
    notes: 'SENT 29 Jul 2026 — 1,464 recipients',
    brand: 'radio-links' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: '2026-07-29T00:00:00.000Z',
    startDate: '2026-07-29T00:00:00.000Z',
    campaignId: null,
    createdAt: '2026-07-29T00:00:00.000Z',
    completedAt: '2026-07-29T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'email-send' as TaskRecord['type'],
    recipients: 1464,
    subject: 'Service & Repair — Radio Links',
  },
  {
    id: 'task-40',
    title: 'Service and Repair Email — IRCL',
    notes: 'SENT 29 Jul 2026 — 243 recipients',
    brand: 'ircl' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: '2026-07-29T00:00:00.000Z',
    startDate: '2026-07-29T00:00:00.000Z',
    campaignId: null,
    createdAt: '2026-07-29T00:00:00.000Z',
    completedAt: '2026-07-29T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'email-send' as TaskRecord['type'],
    recipients: 243,
    subject: 'Service & Repair — IRCL',
  },
  {
    id: 'task-41',
    title: 'Service and Repair Email — IDARO',
    notes: 'SENT 29 Jul 2026 — 51 recipients',
    brand: 'idaro' as TaskRecord['brand'],
    status: 'complete' as TaskRecord['status'],
    priority: 'medium' as TaskRecord['priority'],
    deadline: '2026-07-29T00:00:00.000Z',
    startDate: '2026-07-29T00:00:00.000Z',
    campaignId: null,
    createdAt: '2026-07-29T00:00:00.000Z',
    completedAt: '2026-07-29T00:00:00.000Z',
    previousStatus: null,
    history: [],
    approvalRequired: false,
    approver: null as TaskRecord['approver'],
    blockerReason: null,
    lastBriefGenerated: null,
    source: 'seed',
    sourceConversationId: null,
    type: 'email-send' as TaskRecord['type'],
    recipients: 51,
    subject: 'Service & Repair — IDARO',
  },
];