from pathlib import Path

def replace(path, old, new):
    p = Path(path)
    s = p.read_text()
    if old not in s:
        raise SystemExit(f'pattern not found in {path}: {old[:120]!r}')
    p.write_text(s.replace(old, new, 1))

# Home: canonical entity membership + Known Campaign Spend.
p = 'src/screens/HomeScreen.tsx'
replace(p, "import { filterCampaignsByPeriod, sumSpend } from '@/utils/campaignMetrics';", "import { filterCampaignsByPeriod, filterCampaignsBySelectedEntity } from '@/utils/campaignMetrics';\nimport { getCampaignKnownSpend, sumKnownCampaignSpend } from '@/utils/campaignCosts';")
replace(p, "  const googleAdsPerformance = useAppStore((s) => s.googleAdsPerformance);", "  const googleAdsPerformance = useAppStore((s) => s.googleAdsPerformance);\n  const campaignCosts = useAppStore((s) => s.campaignCosts);")
replace(p, "  const syncGoogleAdsPerformance = useAppStore((s) => s.syncGoogleAdsPerformance);", "  const syncGoogleAdsPerformance = useAppStore((s) => s.syncGoogleAdsPerformance);\n  const syncCampaignCosts = useAppStore((s) => s.syncCampaignCosts);")
replace(p, "  useEffect(() => {\n    syncFundingRecordsFromApi();\n  }, [syncFundingRecordsFromApi]);", "  useEffect(() => {\n    syncFundingRecordsFromApi();\n    syncCampaignCosts();\n  }, [syncFundingRecordsFromApi, syncCampaignCosts]);")
replace(p, "  const googleAdsRange = useMemo(() => resolveGoogleAdsDateRange(period), [period]);\n  useEffect(() => {\n    syncGoogleAdsPerformance(googleAdsRange.startDate, googleAdsRange.endDate);\n  }, [googleAdsRange.startDate, googleAdsRange.endDate, syncGoogleAdsPerformance]);", "  const googleAdsRange = useMemo(() => resolveGoogleAdsDateRange(period), [period]);\n  useEffect(() => {\n    syncGoogleAdsPerformance(googleAdsRange.startDate, googleAdsRange.endDate);\n  }, [googleAdsRange.startDate, googleAdsRange.endDate, syncGoogleAdsPerformance]);\n\n  // Known Campaign Spend is a campaign-lifetime figure. Keep a separate\n  // all-time Google Ads response for it so the same campaign has the same\n  // spend on Overview, Campaigns, Campaign Detail and Performance. The\n  // period-scoped store response above remains the source for PPC KPIs.\n  const [knownSpendGoogleAds, setKnownSpendGoogleAds] = useState<GoogleAdsResponse | null>(null);\n  useEffect(() => {\n    const range = resolveGoogleAdsDateRange('all-time');\n    fetchGoogleAdsPerformance(range.startDate, range.endDate)\n      .then(setKnownSpendGoogleAds)\n      .catch(() => setKnownSpendGoogleAds(null));\n  }, []);")
replace(p, "    () => campaigns.filter((c) => matchesSelectedEntity(c.brand)),", "    () => filterCampaignsBySelectedEntity(campaigns, matchesSelectedEntity),")
replace(p, "  const marketingSpend = useMemo(() => sumSpend(periodCampaigns), [periodCampaigns]);", "  const marketingSpendInfo = useMemo(\n    () => sumKnownCampaignSpend(periodCampaigns, campaignCosts, knownSpendGoogleAds),\n    [periodCampaigns, campaignCosts, knownSpendGoogleAds]\n  );")
replace(p, "        const adsResponse = getGoogleAdsForCampaign(googleAdsPerformance, c);", "        const adsResponse = getGoogleAdsForCampaign(googleAdsPerformance, c);\n        const spendInfo = getCampaignKnownSpend(c, campaignCosts, knownSpendGoogleAds);")
replace(p, "        return { campaign: c, progress, response, nextAction };", "        return { campaign: c, progress, response, nextAction, spendInfo };")
replace(p, "  }, [entityCampaigns, entityTasks, emailPerformance, googleAdsPerformance, onNavigate]);", "  }, [entityCampaigns, entityTasks, emailPerformance, googleAdsPerformance, campaignCosts, knownSpendGoogleAds, onNavigate]);")
replace(p, "                  {activeCampaigns.map(({ campaign: c, progress, response, nextAction }) => (", "                  {activeCampaigns.map(({ campaign: c, progress, response, nextAction, spendInfo }) => (")
replace(p, "                        <div className=\"text-sm\">£{Math.round(c.spend || 0).toLocaleString()}<span className=\"text-xs text-text-secondary\"> manual</span></div>", "                        <div className=\"text-sm\" title={spendInfo.isLegacyFallback ? 'Includes legacy cost requiring classification' : 'Fixed costs + connected media spend'}>\n                          £{Math.round(spendInfo.knownCampaignSpend).toLocaleString()}\n                          {spendInfo.isLegacyFallback && <span className=\"text-xs text-text-secondary\"> legacy cost</span>}\n                        </div>")

# Performance: campaign-lifetime spend, canonical entity matching, modern Infinity page-level metrics.
p = 'src/screens/PerformanceScreen.tsx'
replace(p, "  MARKETING_LEADS_CAVEAT,\n} from '@/utils/campaignMetrics';", "  MARKETING_LEADS_CAVEAT,\n  campaignMatchesSelectedEntity,\n  filterCampaignsBySelectedEntity,\n} from '@/utils/campaignMetrics';")
replace(p, "import { getCallsSnapshot } from '@/utils/channelSnapshot';", "import { resolveCallDateRange, getCallPerformance } from '@/utils/callPerformance';")
replace(p, "import { fetchGa4Traffic, fetchGa4Enquiries, type Ga4TrafficResponse, type Ga4EnquiriesResponse } from '@/services/ga4Api';", "import { fetchGa4Traffic, fetchGa4Enquiries, type Ga4TrafficResponse, type Ga4EnquiriesResponse } from '@/services/ga4Api';\nimport { fetchGoogleAdsPerformance, type GoogleAdsResponse } from '@/services/googleAdsApi';")
replace(p, "  const wave1Performance = useAppStore((s) => s.wave1Performance);", "  const wave1Performance = useAppStore((s) => s.wave1Performance);\n  const infinityCalls = useAppStore((s) => s.infinityCalls);")
replace(p, "  const syncWave1Calls = useAppStore((s) => s.syncWave1Calls);", "  const syncWave1Calls = useAppStore((s) => s.syncWave1Calls);\n  const syncInfinityCalls = useAppStore((s) => s.syncInfinityCalls);")
replace(p, "  const googleAdsRange = useMemo(() => resolveGoogleAdsDateRange(period), [period]);\n  useEffect(() => {\n    syncGoogleAdsPerformance(googleAdsRange.startDate, googleAdsRange.endDate);\n  }, [googleAdsRange.startDate, googleAdsRange.endDate, syncGoogleAdsPerformance]);", "  const googleAdsRange = useMemo(() => resolveGoogleAdsDateRange(period), [period]);\n  useEffect(() => {\n    syncGoogleAdsPerformance(googleAdsRange.startDate, googleAdsRange.endDate);\n  }, [googleAdsRange.startDate, googleAdsRange.endDate, syncGoogleAdsPerformance]);\n\n  // Known Campaign Spend is campaign-lifetime. Fetch all-time media spend\n  // separately so the selected reporting period chooses campaigns, not a\n  // different spend value for the same campaign. Period-scoped Google Ads\n  // above remains the source for PPC performance.\n  const [knownSpendGoogleAds, setKnownSpendGoogleAds] = useState<GoogleAdsResponse | null>(null);\n  useEffect(() => {\n    const range = resolveGoogleAdsDateRange('all-time');\n    fetchGoogleAdsPerformance(range.startDate, range.endDate)\n      .then(setKnownSpendGoogleAds)\n      .catch(() => setKnownSpendGoogleAds(null));\n  }, []);\n\n  const callRange = useMemo(() => resolveCallDateRange(period), [period]);\n  useEffect(() => {\n    syncInfinityCalls(callRange.startDate, callRange.endDate);\n  }, [callRange.startDate, callRange.endDate, syncInfinityCalls]);")
replace(p, "    () => campaigns.filter((c) => matchesSelectedEntity(c.brand)),", "    () => filterCampaignsBySelectedEntity(campaigns, matchesSelectedEntity),")
replace(p, "    () => sumKnownCampaignSpend(periodCampaigns, campaignCosts, googleAdsPerformance),\n    [periodCampaigns, campaignCosts, googleAdsPerformance]", "    () => sumKnownCampaignSpend(periodCampaigns, campaignCosts, knownSpendGoogleAds),\n    [periodCampaigns, campaignCosts, knownSpendGoogleAds]")
replace(p, "  const spendComparison = useMemo(\n    () =>\n      compareToPrevious(\n        marketingSpend,\n        previousRange ? sumKnownCampaignSpend(previousPeriodCampaigns, campaignCosts, googleAdsPerformance).total : null\n      ),\n    [marketingSpend, previousPeriodCampaigns, previousRange, campaignCosts, googleAdsPerformance]\n  );\n", "")
replace(p, "        campaigns.filter((c) => c.brand === brand),", "        campaigns.filter((c) => campaignMatchesSelectedEntity(c, (candidate) => candidate === brand)),")
replace(p, "      const brandSpend = sumKnownCampaignSpend(brandCampaigns, campaignCosts, googleAdsPerformance);", "      const brandSpend = sumKnownCampaignSpend(brandCampaigns, campaignCosts, knownSpendGoogleAds);")
replace(p, "  }, [campaigns, periodStart, ga4Traffic, ga4Enquiries, campaignCosts, googleAdsPerformance, brandAcumaticaSummaries]);", "  }, [campaigns, periodStart, ga4Traffic, ga4Enquiries, campaignCosts, knownSpendGoogleAds, brandAcumaticaSummaries]);")
replace(p, "  const callsSnapshot = useMemo(\n    () => getCallsSnapshot(campaigns, wave1Performance, matchesSelectedEntity),\n    [campaigns, wave1Performance, selectedEntity] // eslint-disable-line react-hooks/exhaustive-deps\n  );", "  const callsSnapshot = useMemo(\n    () => getCallPerformance(infinityCalls, isGroupView, selectedEntity),\n    [infinityCalls, isGroupView, selectedEntity]\n  );")
replace(p, "  const infinityConfigured = wave1Performance?.infinityConfigured === true;", "  const infinityConfigured = infinityCalls?.configured === true;")
replace(p, "    infinityConfigured\n      ? { label: 'Infinity (Calls)', status: (wave1Performance?.infinityErrors?.length ?? 0) > 0 ? 'error' : 'live', detail: (wave1Performance?.infinityErrors?.length ?? 0) > 0 ? 'Sync error' : 'Connected — Wave 1 campaign only' }\n      : { label: 'Infinity (Calls)', status: 'not-connected', detail: 'Not connected' },", "    infinityConfigured\n      ? { label: 'Infinity (Calls)', status: (infinityCalls?.errors?.length ?? 0) > 0 ? 'error' : 'live', detail: (infinityCalls?.errors?.length ?? 0) > 0 ? 'Sync error' : 'Connected' }\n      : { label: 'Infinity (Calls)', status: 'not-connected', detail: 'Not connected' },")
replace(p, "              comparison={spendComparison}\n", "")
replace(p, "              googleAdsPerformance={googleAdsPerformance}", "              googleAdsPerformance={knownSpendGoogleAds}")
replace(p, "            {callsSnapshot ? (\n              <KpiCard title=\"Calls\" value={callsSnapshot.totalCalls} subtitle={`${callsSnapshot.answeredCalls} answered — see Call Tracking`} onClick={() => onNavigate?.('infinity')} size=\"compact\" />\n            ) : (", "            {callsSnapshot.status === 'available' ? (\n              <KpiCard title=\"Calls\" value={callsSnapshot.totalCalls} subtitle={`${callsSnapshot.answeredCalls} answered — see Call Tracking`} onClick={() => onNavigate?.('infinity')} size=\"compact\" />\n            ) : (")
replace(p, "                subtitle={infinityConfigured ? 'No calls scoped to this entity — Wave 1 campaign only' : 'Awaiting Infinity integration'}", "                subtitle={callsSnapshot.subtitle}")
replace(p, "                      ? 'Manual Acumatica export'\n", "                      ? periodStart\n                        ? 'Won opportunities created in selected period — not revenue won during the period'\n                        : 'Latest Acumatica export — no reliable Won Date'\n")

# Leads & CRM: canonical campaign entity membership + honest Won Revenue period wording.
p = 'src/screens/LeadsCrmScreen.tsx'
replace(p, "import { filterCampaignsByPeriod, sumLeads, sumEnquiries, MARKETING_LEADS_CAVEAT } from '@/utils/campaignMetrics';", "import { filterCampaignsByPeriod, filterCampaignsBySelectedEntity, sumLeads, sumEnquiries, MARKETING_LEADS_CAVEAT } from '@/utils/campaignMetrics';")
replace(p, "    () => campaigns.filter((c) => matchesSelectedEntity(c.brand)),", "    () => filterCampaignsBySelectedEntity(campaigns, matchesSelectedEntity),")
replace(p, "                      ? 'Manual Acumatica export'\n", "                      ? periodStart\n                        ? 'Won opportunities created in selected period — not revenue won during the period'\n                        : 'Latest Acumatica export — no reliable Won Date'\n")

# Campaigns: replace local entities[] logic with the shared matcher.
p = 'src/screens/CampaignsScreen.tsx'
replace(p, "import { getKnownCampaignSpend } from '@/utils/campaignCosts';", "import { getKnownCampaignSpend } from '@/utils/campaignCosts';\nimport { campaignMatchesSelectedEntity } from '@/utils/campaignMetrics';")
replace(p, "  const { selectedEntity, isGroupView } = useEntity();", "  const { selectedEntity, isGroupView, matchesSelectedEntity } = useEntity();")
replace(p, "  const campaignEntities = (c: Campaign): Brand[] => (c.entities && c.entities.length > 0 ? c.entities : [c.brand]);\n\n", "")
replace(p, "      if (!isGroupView && !campaignEntities(c).includes(selectedEntity as Brand)) return false;", "      if (!campaignMatchesSelectedEntity(c, matchesSelectedEntity)) return false;")
replace(p, "  }, [campaigns, isGroupView, selectedEntity, filterStatus, filterIndustry, filterVendor, periodStart, searchTerm]);", "  }, [campaigns, matchesSelectedEntity, filterStatus, filterIndustry, filterVendor, periodStart, searchTerm]);")

# Stale attribution comment.
p = 'src/utils/campaignAttribution.ts'
replace(p, "// What this file does NOT cover yet (see the Campaign Attribution phase\n// report for why): GA4 session/enquiry attribution needs new backend query\n// support (an exact sessionCampaignName match against a campaign's own\n// Tracking Link utmCampaign values) that hasn't shipped yet. Until that\n// lands, GA4 campaign-level figures stay \"Not connected\" on Campaign\n// Detail rather than guessing from date/volume alone.\n", "// GA4 campaign attribution is now supported separately through explicit\n// campaign.ga4CampaignNames[] exact matches against sessionCampaignName.\n// This file continues to own Google Ads and Infinity matching; it does not\n// invent per-enquiry identity or CRM attribution where no deterministic key\n// exists.\n")

# MCP: reject the legacy spend write rather than bypassing Campaign Costs.
p = 'backend/src/services/actionService.ts'
replace(p, "  actualSpend: z.number().optional().describe('Actual spend in £ — the field shown as \"Actual spend (£)\" on the campaign card. Overwritten automatically the next time a linked task\\'s cost changes, so prefer setting task costs where possible.'),", "  actualSpend: z.number().optional().describe('Deprecated legacy campaign.spend field. MCP writes are rejected; use the authenticated Campaign Costs UI/API so spend remains classified.'),")
replace(p, "  if (!existing) {\n    return { success: false, action: 'update_campaign', message: `No campaign found with id ${input.campaign_id}.` };\n  }\n\n  if (!confirmed) {", "  if (!existing) {\n    return { success: false, action: 'update_campaign', message: `No campaign found with id ${input.campaign_id}.` };\n  }\n\n  // Structured Campaign Costs are the canonical spend model. Keep MCP\n  // least-privilege intact: do not expose campaign_costs through generic\n  // MCP access, and do not let this legacy field silently bypass cost\n  // classification by writing campaigns.spend.\n  if (input.actualSpend !== undefined) {\n    return {\n      success: false,\n      action: 'update_campaign',\n      message: 'actualSpend is no longer writable through MCP. Record classified spend through Campaign Costs in the authenticated dashboard/API.',\n    };\n  }\n\n  if (!confirmed) {")
replace(p, "  if (input.actualSpend !== undefined) updates.spend = input.actualSpend;\n", "")

# Acumatica comment: make Created On period semantics explicit without changing KPI rules.
p = 'backend/src/services/acumaticaReporting.ts'
replace(p, "// Shared entity/period scoping — the ONE place that decides which real\n// imported opportunities are \"in scope\" for a given brand/date-range\n// selection, so getAcumaticaSummary", "// Shared entity/period scoping — the ONE place that decides which real\n// imported opportunities are \"in scope\" for a given brand/date-range.\n// Date ranges are based on Opportunity Created On because the export has no\n// trustworthy Won Date. Consequently period-scoped Won Deals/Won Revenue mean\n// \"currently Won opportunities created in this period\", never \"won during\n// this period\". UI consumers must label that distinction explicitly.\n// This selection is shared so getAcumaticaSummary")

print('Phase 1 patch applied')
